version: '3.1'

services:
  db:
    image: "postgres"
    restart: "always"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blog
    ports:
      - "6000:5432"
  backend:
    build: .
    restart: "always"
    stdin_open: true
    tty: true
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
    volumes:
      - static_data:/app/static
  frontend:
    build: ./frontend
    ports: 
      - "8080:8080"

volumes:
  static_data:
    